/-
Copyright (c) 2026 Carlo Perassi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
-- The full Mathlib import is deliberate. With a narrower import set the
-- `Fintype (Fin 2)` instance behind `∑ i, ∑ j` resolves to `Fin.fintype 2`,
-- whereas in `Solution` (which imports all of Mathlib through `Diaz`) it
-- resolves to `SimplexCategory.instFintypeToTypeOrderHomFinHAddNatLenOfNat`.
-- The two are definitionally equal but not syntactically equal, and Comparator
-- compares statements as elaborated terms, so it rejects the pair. Importing
-- the same closure in both modules makes the statements identical on the nose.
import Mathlib

/-!
# Advertised statement: conjugation on a hull is not independent data

Let `K ⊆ ℂ` be a subfield closed under complex conjugation and let `u ∈ ℂ`
satisfy `u * conj u ∈ K`.  The intended case is `K = ℚ̄` and `u` a hypothetical
counterexample to Diaz's question: `u ≠ 0`, `exp u` algebraic, `|u|` algebraic.

The mechanism is one identity, `conj_eq_rho_div`: for `u ≠ 0`,
`conj u = (u * conj u)/u`.  So on the subfield generated by `K` and `u`,
conjugation is a rational function of the generator, not extra structure a
homomorphism might fail to respect.  Three consequences are stated here:
a homomorphism fixing `K` and moving `u` to another point of the same circle
intertwines conjugation automatically (`conj_comm`); such a homomorphism exists
on the hull whenever both points are transcendental over `K`
(`exists_algHom_of_transcendental`); and no vanishing-coefficient statement over
`K` built from the rank-one matrix `Hmat` separates the two points
(`coeff_indistinguishable`).

**Scope.** These are negative results about a class of proof strategies. No
transcendence result is proved, and Diaz's question is untouched: nothing here
bears on whether a non-zero logarithm of an algebraic number can have algebraic
modulus. Statements are proved for an arbitrary conjugation-stable `K`, so the
formalization never asserts that any such `u` exists.
-/

open ComplexConjugate

namespace DiazRigidity

/-- The subfield of `ℂ` generated by `K` together with `u`. -/
noncomputable def hull (K : Subfield ℂ) (u : ℂ) : Subfield ℂ :=
  Subfield.closure ((K : Set ℂ) ∪ {u})

/-- The matrix `H` attached to a point of the circle `z * conj z = r ^ 2`. -/
noncomputable def Hmat (u r : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  !![u, r; r, conj u]

/-- **The mechanism.**  The conjugate of `u` is a rational function of `u`,
with the single coefficient `u * conj u`. -/
theorem conj_eq_rho_div {u : ℂ} (hu : u ≠ 0) :
    u * conj u / u = conj u := by
  sorry

/-- **Rigidity.**  Two ring homomorphisms of `ℂ` agreeing on `K` and at `u`
agree on the whole hull: a homomorphism is determined by those data. -/
theorem eqOn_hull {K : Subfield ℂ} {u : ℂ} (f g : ℂ →+* ℂ)
    (hK : ∀ z ∈ K, f z = g z) (hu : f u = g u) :
    ∀ z ∈ hull K u, f z = g z := by
  sorry

/-- **The intertwining is forced.**  A ring homomorphism fixing `K` pointwise
and carrying `u` to a point `t` of the same circle commutes with complex
conjugation on the whole hull of `u`.  Nothing is arranged: it follows from
`conj_eq_rho_div` together with `eqOn_hull`. -/
theorem conj_comm {K : Subfield ℂ} {u t : ℂ} (Φ : ℂ →+* ℂ)
    (hK : ∀ a ∈ K, Φ a = a) (hKconj : ∀ a ∈ K, conj a ∈ K)
    (hu0 : u ≠ 0) (ht0 : t ≠ 0) (hΦu : Φ u = t)
    (hρ : u * conj u ∈ K) (hρt : t * conj t = u * conj u) :
    ∀ z ∈ hull K u, Φ (conj z) = conj (Φ z) := by
  sorry

/-- **Existence, on the hull.**  If `u` and `t` are both transcendental over
`K`, some `K`-algebra map from `K⟮u⟯` into `ℂ` carries `u` to `t`.  Both fields
are rational function fields over `K`, hence `K`-isomorphic. -/
theorem exists_algHom_of_transcendental {K : Subfield ℂ} {u t : ℂ}
    (hu : Transcendental (↥K) u) (ht : Transcendental (↥K) t) :
    ∃ Φ : ↥(IntermediateField.adjoin (↥K) {u}) →ₐ[↥K] ℂ,
      Φ (IntermediateField.AdjoinSimple.gen (↥K) u) = t := by
  sorry

/-- **No coefficient vanishes.**  For a point `u ∉ K` of the circle
`z * conj z = r ^ 2` and non-zero vectors `w, v` over `K`, the coefficient
`wᵀ H v` is non-zero. -/
theorem no_vanishing_coeff_matrix {K : Subfield ℂ} {u r : ℂ}
    (hr : r ∈ K) (huK : u ∉ K) (h : u * conj u = r ^ 2)
    (w v : Fin 2 → ℂ) (hwK : ∀ i, w i ∈ K) (hvK : ∀ j, v j ∈ K)
    (hw : w ≠ 0) (hv : v ≠ 0) :
    ∑ i, ∑ j, w i * Hmat u r i j * v j ≠ 0 := by
  sorry

/-- **The negative result.**  Two points off `K` on the same circle over `K`
are not separated by any vanishing-coefficient statement over `K`: the
coefficient vanishes for one exactly when it vanishes for the other. -/
theorem coeff_indistinguishable {K : Subfield ℂ} {u t r : ℂ}
    (hr : r ∈ K) (huK : u ∉ K) (htK : t ∉ K)
    (hu : u * conj u = r ^ 2) (ht : t * conj t = r ^ 2)
    (w v : Fin 2 → ℂ) (hwK : ∀ i, w i ∈ K) (hvK : ∀ j, v j ∈ K)
    (hw : w ≠ 0) (hv : v ≠ 0) :
    (∑ i, ∑ j, w i * Hmat u r i j * v j = 0) ↔
      (∑ i, ∑ j, w i * Hmat t r i j * v j = 0) := by
  sorry

end DiazRigidity
