import Diaz.Axioms
import Diaz.Closure
import Diaz.Exponential
import Diaz.Model
import Diaz.Nodes
import Diaz.Rigidity
import Diaz.Instantiation
import Diaz.Transfer
import Diaz.Multipliers
import Diaz.SFE
import Diaz.Quantisation
import Diaz.Line
import Diaz.Pencil
import Diaz.NoGo
import Diaz.Palomar
