import Diaz.Axioms
import Diaz.Closure
import Diaz.Exponential
import Diaz.Model
import Diaz.Nodes
import Diaz.Rigidity
import Diaz.Instantiation
import Diaz.Transfer
import Diaz.Multipliers
import Diaz.Kernel
import Diaz.HermiteLindemann
import Diaz.SFE
import Diaz.Quantisation
import Diaz.Line
import Diaz.CheapLine
import Diaz.Pencil
import Diaz.NoGo
import Diaz.P21P
import Diaz.Fibre
import Diaz.Palomar
