name = "Diaz"
version = "0.1.0"
defaultTargets = ["Diaz", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "Diaz"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
