/-
Copyright (c) 2026 Carlo Perassi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Diaz
import Mathlib

/-!
# Proved solution

The proved counterparts of the declarations advertised in `Challenge.lean`.
Comparator checks that each has exactly the same name and type as its
counterpart there, and that none depends on `sorryAx`, `Lean.ofReduceBool`, a
custom axiom, or an unnamed missing definition.

`hull` and `Hmat` are repeated with bodies identical to those in `Challenge.lean`
and to those in `Diaz.Closure` / `Diaz.Rigidity`, so the proofs below delegate by
definitional equality.

The wider development in `Diaz/` also imports two transcendence results as
axioms, `Diaz.hermite_lindemann` and `Diaz.exists_ringHom_of_transcendental`.
Nothing in this module depends on either; the `#print axioms` audit at the foot
of the file is the check.
-/

open ComplexConjugate

namespace DiazRigidity

/-- The subfield of `ℂ` generated by `K` together with `u`. -/
noncomputable def hull (K : Subfield ℂ) (u : ℂ) : Subfield ℂ :=
  Subfield.closure ((K : Set ℂ) ∪ {u})

/-- The matrix `H` attached to a point of the circle `z * conj z = r ^ 2`. -/
noncomputable def Hmat (u r : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  !![u, r; r, conj u]

/-- **The mechanism.**  The conjugate of `u` is a rational function of `u`,
with the single coefficient `u * conj u`. -/
theorem conj_eq_rho_div {u : ℂ} (hu : u ≠ 0) :
    u * conj u / u = conj u :=
  Diaz.conj_eq_rho_div hu

/-- **Rigidity.**  Two ring homomorphisms of `ℂ` agreeing on `K` and at `u`
agree on the whole hull. -/
theorem eqOn_hull {K : Subfield ℂ} {u : ℂ} (f g : ℂ →+* ℂ)
    (hK : ∀ z ∈ K, f z = g z) (hu : f u = g u) :
    ∀ z ∈ hull K u, f z = g z :=
  Diaz.eqOn_hull f g hK hu

/-- **The intertwining is forced.** -/
theorem conj_comm {K : Subfield ℂ} {u t : ℂ} (Φ : ℂ →+* ℂ)
    (hK : ∀ a ∈ K, Φ a = a) (hKconj : ∀ a ∈ K, conj a ∈ K)
    (hu0 : u ≠ 0) (ht0 : t ≠ 0) (hΦu : Φ u = t)
    (hρ : u * conj u ∈ K) (hρt : t * conj t = u * conj u) :
    ∀ z ∈ hull K u, Φ (conj z) = conj (Φ z) :=
  Diaz.conj_comm Φ hK hKconj hu0 ht0 hΦu hρ hρt

/-- **Existence, on the hull**, without the Steinitz axiom. -/
theorem exists_algHom_of_transcendental {K : Subfield ℂ} {u t : ℂ}
    (hu : Transcendental (↥K) u) (ht : Transcendental (↥K) t) :
    ∃ Φ : ↥(IntermediateField.adjoin (↥K) {u}) →ₐ[↥K] ℂ,
      Φ (IntermediateField.AdjoinSimple.gen (↥K) u) = t :=
  Diaz.exists_algHom_of_transcendental hu ht

/-- **No coefficient vanishes.** -/
theorem no_vanishing_coeff_matrix {K : Subfield ℂ} {u r : ℂ}
    (hr : r ∈ K) (huK : u ∉ K) (h : u * conj u = r ^ 2)
    (w v : Fin 2 → ℂ) (hwK : ∀ i, w i ∈ K) (hvK : ∀ j, v j ∈ K)
    (hw : w ≠ 0) (hv : v ≠ 0) :
    ∑ i, ∑ j, w i * Hmat u r i j * v j ≠ 0 :=
  Diaz.no_vanishing_coeff_matrix hr huK h w v hwK hvK hw hv

/-- **The negative result.** -/
theorem coeff_indistinguishable {K : Subfield ℂ} {u t r : ℂ}
    (hr : r ∈ K) (huK : u ∉ K) (htK : t ∉ K)
    (hu : u * conj u = r ^ 2) (ht : t * conj t = r ^ 2)
    (w v : Fin 2 → ℂ) (hwK : ∀ i, w i ∈ K) (hvK : ∀ j, v j ∈ K)
    (hw : w ≠ 0) (hv : v ≠ 0) :
    (∑ i, ∑ j, w i * Hmat u r i j * v j = 0) ↔
      (∑ i, ∑ j, w i * Hmat t r i j * v j = 0) :=
  Diaz.coeff_indistinguishable hr huK htK hu ht w v hwK hvK hw hv

end DiazRigidity

/-! ## Axiom audit

Every compared declaration must depend only on `propext`, `Classical.choice`
and `Quot.sound`.  In particular none may depend on `Diaz.hermite_lindemann` or
`Diaz.exists_ringHom_of_transcendental`. -/

#print axioms DiazRigidity.hull
#print axioms DiazRigidity.Hmat
#print axioms DiazRigidity.conj_eq_rho_div
#print axioms DiazRigidity.eqOn_hull
#print axioms DiazRigidity.conj_comm
#print axioms DiazRigidity.exists_algHom_of_transcendental
#print axioms DiazRigidity.no_vanishing_coeff_matrix
#print axioms DiazRigidity.coeff_indistinguishable
