/-
Mirrored from Prove2Me: `GelfondSchneider.common_field`.

Ported mechanically from the accepted submission archived as
`archive/prove2me/GelfondSchneider.common_field__4263f0e8.lean`. Statement and proof are the platform's; only
imports, namespaces and the theorem's name were rewritten.
-/
import Mathlib

namespace GelfondSchneider

open NumberField

namespace GS_field

open IntermediateField

-- The field `ℚ⟮a, b, c⟯ ⊆ ℂ` generated by three algebraic numbers is a number field:
-- characteristic zero is inherited from `ℚ`, and it is finite-dimensional since the
-- adjoined generators are integral over `ℚ`.
lemma isNumberField_adjoin (a b c : ℂ) (ha : IsAlgebraic ℚ a) (hb : IsAlgebraic ℚ b)
    (hc : IsAlgebraic ℚ c) : NumberField (adjoin ℚ ({a, b, c} : Set ℂ)) where
  to_charZero := charZero_of_injective_algebraMap (algebraMap ℚ _).injective
  to_finiteDimensional := finiteDimensional_adjoin fun _ hx ↦ by
    rcases hx with rfl | rfl | rfl
    exacts [isAlgebraic_iff_isIntegral.1 ha, isAlgebraic_iff_isIntegral.1 hb,
      isAlgebraic_iff_isIntegral.1 hc]

-- Three algebraic numbers lie in a common number field, embedded in `ℂ` by its inclusion.
lemma exists_common_field (a b c : ℂ) (ha : IsAlgebraic ℚ a) (hb : IsAlgebraic ℚ b)
    (hc : IsAlgebraic ℚ c) :
    ∃ (K : Type) (_ : Field K) (_ : NumberField K) (σ : K →+* ℂ) (a' b' c' : K),
      σ a' = a ∧ σ b' = b ∧ σ c' = c := by
  refine ⟨adjoin ℚ ({a, b, c} : Set ℂ), inferInstance, isNumberField_adjoin a b c ha hb hc,
    (adjoin ℚ ({a, b, c} : Set ℂ)).val.toRingHom,
    ⟨a, subset_adjoin _ _ (by simp)⟩, ⟨b, subset_adjoin _ _ (by simp)⟩,
    ⟨c, subset_adjoin _ _ (by simp)⟩, rfl, rfl, rfl⟩

end GS_field

open GS_field in
theorem common_field (l β : ℂ) (hβ : IsAlgebraic ℚ β) (hα : IsAlgebraic ℚ (Complex.exp l))
    (hγ : IsAlgebraic ℚ (Complex.exp (β * l))) :
    ∃ (K : Type) (_ : Field K) (_ : NumberField K) (σ : K →+* ℂ) (α' β' γ' : K),
      σ α' = Complex.exp l ∧ σ β' = β ∧ σ γ' = Complex.exp (β * l) := by
  exact exists_common_field _ _ _ hα hβ hγ

end GelfondSchneider
