#!/usr/bin/env python3
"""Generate the blueprint chapters from the Prove2Me archive and the curated node files.

The blueprint covers the classical part of the library: the theorems marked `root = true` in
blueprint/nodes/*.toml (the table "The classical theorems" of the README) and every
Prove2Me node their accepted proofs import, transitively.

Inputs
  archive/prove2me/manifest.json and the accepted proofs beside it. The dependencies of a
      node are the `import Theorems.Thm_<name>` lines of its accepted proof: the latest
      ACCEPTED submission, or the latest sketch when there is none. These are the proofs
      that Diaz/Mirror/ ports.
  MIRROR_CHECKLIST.md and the Lean files it names: the library name of each node, which is
      what `\\lean{}` must carry. A node file can give `lean = [...]` instead.
  blueprint/nodes/NN-<chapter>.toml: one file per chapter, in order. A chapter file has a
      [chapter] table (title, introductory text) and a [[node]] entry per node, in the order
      of the chapter, with the statement in LaTeX, the attribution and a proof sketch. The
      statements are written by hand from the Prove2Me pages and checked against the Lean
      statements; `from_lean = true` marks those written from the Lean source instead.
      References for \\cite live in the [[reference]] entries of any node file.
  blueprint/cache/<theorem name>.json: the node's Prove2Me page, GET /theorems/<id> without
      its `audits` and `vote_count`, saved by scripts/fetch_blueprint_cache.sh: the text the
      statements were checked against, and the draft for a node that has no entry yet.
  Diaz/**/*.lean: the line where each \\lean{} name is declared.

Outputs
  blueprint/src/content.tex and blueprint/src/chapters/*.tex. Do not edit them by hand.
  blueprint/src/macros/stats.tex: \\blueprintresults, the number of results, for web.tex.
  blueprint/docs-find/decls.json: each \\lean{} name and the GitHub URL of the line that
      declares it. The site's Lean links go to docs/find/#doc/<name>, where doc-gen4 would
      answer; until there are doc-gen4 pages, blueprint/docs-find/index.html is served there
      and redirects through this file. A name that cannot be located is an error.

Usage
  python3 scripts/gen_blueprint.py           regenerate the chapters
  python3 scripts/gen_blueprint.py --check   exit 1 if regenerating would change a file
  python3 scripts/gen_blueprint.py --stubs   also emit nodes that have no entry yet, with the
                                             page text as a draft, instead of failing
  python3 scripts/gen_blueprint.py --missing print "name<TAB>theorem id" for every node of
                                             the closure with no cached page

Adding results (Baker's theorem, say): mark the new headline nodes `root = true` in a new
chapter file, run --missing and fetch those pages, run --stubs to see the drafts, then write
the entries and regenerate.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARCHIVE = ROOT / "archive" / "prove2me"
BLUEPRINT = ROOT / "blueprint"
NODE_DIR = BLUEPRINT / "nodes"
CACHE = BLUEPRINT / "cache"
SRC = BLUEPRINT / "src"
CHAPTER_DIR = SRC / "chapters"
DOCS_FIND = BLUEPRINT / "docs-find"
BRANCH = "master"  # the branch the Lean links point into

GENERATED = "% Generated by scripts/gen_blueprint.py from blueprint/nodes/{stem}.toml. Do not edit.\n"
ENV_PREFIX = {"theorem": "thm", "lemma": "lem", "proposition": "prop", "corollary": "cor", "definition": "def"}


def fail(msg: str) -> None:
    sys.exit(f"gen_blueprint: {msg}")


# --- The archive: nodes, accepted proofs, import edges -------------------------------------

def load_manifest() -> dict[str, list[dict]]:
    by_name: dict[str, list[dict]] = {}
    for entry in json.loads((ARCHIVE / "manifest.json").read_text()):
        by_name.setdefault(entry["theorem_name"], []).append(entry)
    return by_name


def chosen_submission(entries: list[dict]) -> dict:
    accepted = [e for e in entries if e["status"] == "ACCEPTED"]
    return max(accepted or entries, key=lambda e: e["created_at"])


IMPORT_RE = re.compile(r"^import\s+Theorems\.(Thm_\S+)", re.M)


def import_closure(roots: list[str], by_name: dict[str, list[dict]]) -> dict[str, list[str]]:
    module_to_name: dict[str, str] = {}
    for name in by_name:
        module = "Thm_" + name.replace(".", "_")
        if module in module_to_name:
            fail(f"{name} and {module_to_name[module]} have the same module name {module}")
        module_to_name[module] = name
    deps: dict[str, list[str]] = {}
    stack = list(roots)
    while stack:
        name = stack.pop()
        if name in deps:
            continue
        if name not in by_name:
            fail(f"{name} has no accepted proof in archive/prove2me/manifest.json")
        text = (ARCHIVE / chosen_submission(by_name[name])["file"]).read_text()
        out = []
        for module in IMPORT_RE.findall(text):
            if module not in module_to_name:
                fail(f"{name} imports Theorems.{module}, which has no accepted proof in the archive")
            out.append(module_to_name[module])
        deps[name] = out
        stack.extend(out)
    return deps


# --- The library: the Lean name of each node -----------------------------------------------

def mirror_rows() -> dict[str, str]:
    rows = {}
    for line in (ROOT / "MIRROR_CHECKLIST.md").read_text().splitlines():
        m = re.match(r"\| `([^`]+)` \| \w+ \| `([^`]+)` \|", line)
        if m:
            rows[m.group(1)] = m.group(2)
    return rows


DECL_RE = re.compile(r"(?:@\[[^\]]*\]\s*)?(?:protected |private |nonrec )?(?:theorem|lemma) (\S+)")


def declared_names(path: Path, short: str) -> list[str]:
    """Full names of the top-level theorems called `short` in `path`, tracking namespaces."""
    stack: list[str] = []
    found = []
    for line in path.read_text().splitlines():
        if m := re.match(r"namespace (\S+)", line):
            stack.append(m.group(1))
        elif (m := re.match(r"end (\S+)\s*$", line)) and stack and stack[-1] == m.group(1):
            stack.pop()
        elif (m := DECL_RE.match(line)) and m.group(1).split(".")[-1] == short:
            found.append(".".join(stack + [m.group(1)]))
    return found


DECL_LINE_RE = re.compile(r"^(?:@\[[^\]]*\]\s*)*"
                          r"((?:(?:private|protected|public|noncomputable|nonrec|partial|unsafe)\s+)*)"
                          r"(?:theorem|lemma|def|abbrev)\s+([^\s:({\[]+)")
SECTION_RE = re.compile(r"^(?:@\[[^\]]*\]\s*)*(?:(?:public|noncomputable)\s+)*section\b(?:\s+(\S+))?")


def declaration_lines() -> dict[str, list[tuple[str, int]]]:
    """Where each public theorem, lemma or def of the library is declared: (path, line)."""
    index: dict[str, list[tuple[str, int]]] = {}
    for path in sorted((ROOT / "Diaz").rglob("*.lean")):
        rel = path.relative_to(ROOT).as_posix()
        scopes: list[tuple[str, str]] = []  # ("namespace" | "section", name)
        comment = 0  # depth of block comments
        for number, line in enumerate(path.read_text().splitlines(), 1):
            if comment == 0:
                if m := re.match(r"namespace (\S+)", line):
                    scopes.append(("namespace", m.group(1)))
                elif m := SECTION_RE.match(line):
                    scopes.append(("section", m.group(1) or ""))
                elif m := re.match(r"end(?:\s+(\S+))?\s*$", line):
                    if scopes and scopes[-1][1] == (m.group(1) or ""):
                        scopes.pop()
                elif (m := DECL_LINE_RE.match(line)) and "private" not in m.group(1):
                    name = m.group(2).rstrip(".")  # `foo.{u}` names `foo`
                    if name.startswith("_root_."):
                        full = name[len("_root_."):]
                    else:
                        full = ".".join([n for kind, n in scopes if kind == "namespace"] + [name])
                    index.setdefault(full, []).append((rel, number))
            comment = max(0, comment + line.count("/-") - line.count("-/"))
    return index


def repository_url() -> str:
    m = re.search(r"\\github\{([^}]*)\}", (SRC / "web.tex").read_text())
    if not m:
        fail("no \\github{...} in blueprint/src/web.tex")
    return m.group(1).rstrip("/")


def library_names(platform: str, rows: dict[str, str]) -> list[str]:
    short = platform.split(".")[-1]
    rel = rows.get(platform, f"Diaz/Mirror/{short}.lean")
    path = ROOT / rel
    if not path.exists():
        return []
    return declared_names(path, short)


# --- Curated data ---------------------------------------------------------------------------

@dataclass
class Node:
    platform: str
    chapter: str
    env: str
    label: str
    lean: list[str]
    title: str = ""
    section: str = ""
    statement: str = ""
    source: str = ""
    sketch: str = ""
    from_lean: bool = False
    note: str = ""
    root: bool = False
    stub: bool = False
    ids: dict[str, str] = field(default_factory=dict)  # platform name -> Prove2Me theorem id
    also: list[str] = field(default_factory=list)  # platform nodes merged into this one
    uses: list[str] = field(default_factory=list)  # labels


@dataclass
class Chapter:
    stem: str
    title: str
    text: str
    nodes: list[Node] = field(default_factory=list)


def load_curated():
    chapters: list[Chapter] = []
    entries: dict[str, tuple[str, dict]] = {}
    references: list[dict] = []
    for path in sorted(NODE_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        references.extend(data.get("reference", []))
        if "chapter" not in data:
            continue
        chapters.append(Chapter(path.stem, data["chapter"]["title"], data["chapter"].get("text", "")))
        for entry in data.get("node", []):
            name = entry["platform"]
            if name in entries:
                fail(f"{name} has two entries ({entries[name][0]}, {path.stem})")
            entries[name] = (path.stem, entry)
    return chapters, entries, references


def page(name: str) -> dict | None:
    path = CACHE / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


# --- Markdown page text to LaTeX, for drafts --------------------------------------------------

SPECIAL = {"\\": r"\textbackslash{}", "#": r"\#", "%": r"\%", "&": r"\&", "_": r"\_",
           "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
STOP = re.compile(r"^\s*(\*\*(Novelty|What it is for|Why|Proof|Formali[sz]ation|Role|Attribution|"
                  r"Honesty|Intended proof|Where it anchors)|---)", re.M)


def _text(s: str) -> str:
    s = "".join(SPECIAL.get(c, c) for c in s)
    s = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", s)
    s = re.sub(r"`([^`]+)`", r"\\texttt{\1}", s)
    s = re.sub(r"(?<![*\w])\*([^*\n]+)\*(?![*\w])", r"\\emph{\1}", s)
    return s


def markdown_to_latex(md: str) -> str:
    """A draft: the page text up to its first commentary heading, with math kept as is."""
    if m := STOP.search(md):
        md = md[: m.start()]
    out, pos = [], 0
    for m in re.finditer(r"\$\$(.+?)\$\$|\$(.+?)\$", md, re.S):
        out.append(_text(md[pos:m.start()]))
        out.append(f"\\[{m.group(1)}\\]" if m.group(1) is not None else f"${m.group(2)}$")
        pos = m.end()
    out.append(_text(md[pos:]))
    lines = []
    in_list = False
    for line in "".join(out).strip().splitlines():
        if line.startswith("- "):
            if not in_list:
                lines.append("\\begin{itemize}")
                in_list = True
            lines.append("\\item " + line[2:])
            continue
        if in_list:
            lines.append("\\end{itemize}")
            in_list = False
        lines.append(line)
    if in_list:
        lines.append("\\end{itemize}")
    return "\n".join(lines)


# --- Assembly --------------------------------------------------------------------------------

def build(allow_stubs: bool):
    chapters, entries, references = load_curated()
    if not chapters:
        fail("no chapter files in blueprint/nodes/")
    by_name = load_manifest()
    roots = [name for name, (_, e) in entries.items() if e.get("root")]
    deps = import_closure(roots, by_name)
    rows = mirror_rows()

    unknown = sorted(set(entries) - set(deps))
    if unknown:
        fail("entries for nodes outside the closure of the roots: " + ", ".join(unknown))

    nodes: dict[str, Node] = {}
    merged: dict[str, str] = {}  # platform name -> platform name of the node that carries it
    stubs = sorted(set(deps) - set(entries)) if allow_stubs else []
    if stubs:
        chapters.append(Chapter("99-drafts", "Drafts", "Nodes with no entry yet, from their page text."))
        for name in stubs:
            entries[name] = ("99-drafts", {"platform": name, "stub": True})
    chapter_of = {c.stem: c for c in chapters}
    missing = sorted(set(deps) - set(entries))
    if missing:
        fail("nodes of the closure with no entry in blueprint/nodes/ (run with --stubs for drafts): "
             + ", ".join(missing))

    for name, (stem, e) in entries.items():
        if "same_as" in e:
            merged[name] = e["same_as"]
            continue
        short = name.split(".")[-1]
        env = e.get("env", "lemma")
        if env not in ENV_PREFIX:
            fail(f"{name}: env = {env!r}; use one of {', '.join(ENV_PREFIX)}")
        derived = library_names(name, rows)
        lean = e.get("lean") or derived
        if len(lean) == 0:
            fail(f"{name}: no Lean declaration found; give `lean = [...]` in {stem}.toml")
        if "lean" in e and derived and derived != e["lean"]:
            print(f"warning: {name}: lean = {e['lean']} but the mirror declares {derived}", file=sys.stderr)
        p = page(name)
        node = Node(
            platform=name, chapter=stem, env=env,
            label=e.get("label", f"{ENV_PREFIX[env]}:{short}"), lean=lean,
            title=e.get("title", ""), section=e.get("section", ""),
            statement=e.get("statement", ""), source=e.get("source", ""), sketch=e.get("sketch", ""),
            from_lean=e.get("from_lean", False), note=e.get("note", ""), root=e.get("root", False),
            stub=e.get("stub", False),
        )
        if node.stub:
            node.title = (p or {}).get("theorem_title") or ""
            node.statement = markdown_to_latex((p or {}).get("natural_language_statement") or "")
            node.source = _text((p or {}).get("source") or "")
        if not node.statement.strip():
            fail(f"{name}: empty statement")
        nodes[name] = node
        chapter_of[stem].nodes.append(node)

    for name, target in merged.items():
        if target not in nodes:
            fail(f"{name}: same_as {target}, which has no entry of its own")
        nodes[target].also.append(name)
    for node in nodes.values():
        node.ids = {name: by_name[name][0]["theorem_id"] for name in [node.platform] + node.also}

    def carrier(name: str) -> Node:
        return nodes[merged.get(name, name)]

    labels = [n.label for n in nodes.values()]
    if len(labels) != len(set(labels)):
        fail("duplicate labels: " + ", ".join(sorted({l for l in labels if labels.count(l) > 1})))

    for node in nodes.values():
        e = entries[node.platform][1]
        sources = [node.platform] + node.also
        if "uses" in e:  # an override, with its reason in `uses_note`
            used = e["uses"]
            for d in used:
                if d not in nodes and d not in merged:
                    fail(f"{node.platform}: uses {d}, which has no entry")
        else:
            used = [d for s in sources for d in deps[s]]
        seen = []
        for d in used:
            label = carrier(d).label
            if label != node.label and label not in seen:
                seen.append(label)
        node.uses = seen

    # No result may use one that comes later in the blueprint.
    position = {}
    for c in chapters:
        for n in c.nodes:
            position[n.label] = len(position)
    for c in chapters:
        for n in c.nodes:
            for u in n.uses:
                if position[u] > position[n.label]:
                    msg = f"{n.platform} ({c.stem}) uses {u}, which comes later; reorder the node files"
                    if stubs:
                        print(f"warning: {msg}", file=sys.stderr)
                    else:
                        fail(msg)

    # Every \ref and \cite must resolve.
    ref_keys = {r["key"] for r in references}
    targets = set(labels) | {f"chap:{c.stem}" for c in chapters}
    all_text = "\n".join([c.text for c in chapters] +
                         [n.statement + n.source + n.sketch for n in nodes.values()])
    for m in re.finditer(r"\\ref\{([^}]*)\}", all_text):
        if m.group(1) not in targets:
            fail(f"\\ref{{{m.group(1)}}} does not resolve")
    for m in re.finditer(r"\\cite(?:\[[^\]]*\])?\{([^}]*)\}", all_text):
        for key in m.group(1).split(","):
            if key.strip() not in ref_keys:
                fail(f"\\cite{{{key.strip()}}} has no [[reference]] entry")

    # The Lean links: the line that declares each \lean{} name, on GitHub.
    index = declaration_lines()
    repo = repository_url()
    links: dict[str, str] = {}
    for n in nodes.values():
        for name in n.lean:
            places = index.get(name, [])
            if len(places) != 1:
                where = ", ".join(f"{p}:{line}" for p, line in places)
                fail(f"\\lean{{{name}}} ({n.platform}): " +
                     (f"declared more than once ({where})" if places else "no declaration found in Diaz/"))
            path, line = places[0]
            links[name] = f"{repo}/blob/{BRANCH}/{path}#L{line}"
    return chapters, nodes, references, stubs, deps, links


def node_tex(n: Node) -> str:
    out = []
    for name, tid in n.ids.items():
        out.append(f"% Prove2Me: {name} -- https://prove2.me/theorems/{tid}")
    if n.from_lean:
        out.append("% Statement written from the Lean source" + (f": {n.note}" if n.note else "."))
    if n.stub:
        out.append("% DRAFT: page text, not yet checked against the Lean statement.")
    opt = f"[{n.title}]" if n.title else ""
    out.append(f"\\begin{{{n.env}}}{opt}")
    out.append(f"\\label{{{n.label}}}")
    out.append(f"\\lean{{{', '.join(n.lean)}}}")
    out.append("\\leanok")
    out.append(n.statement.strip())
    if n.source.strip():
        out.append("")
        out.append(f"{{\\small\\emph{{Source:}} {n.source.strip()}}}")
    out.append(f"\\end{{{n.env}}}")
    out.append("")
    out.append("\\begin{proof}")
    out.append("\\leanok")
    if n.uses:
        out.append(f"\\uses{{{','.join(n.uses)}}}")
    if n.sketch.strip():
        out.append(n.sketch.strip())
    out.append("\\end{proof}")
    return "\n".join(out) + "\n"


def render(chapters, references, links) -> dict[Path, str]:
    files: dict[Path, str] = {}
    files[DOCS_FIND / "decls.json"] = json.dumps(dict(sorted(links.items())), indent=1) + "\n"
    results = sum(len(c.nodes) for c in chapters)
    files[SRC / "macros" / "stats.tex"] = (GENERATED.format(stem="*") +
                                          f"\\newcommand{{\\blueprintresults}}{{{results}}}\n")
    inputs = []
    for c in chapters:
        parts = [GENERATED.format(stem=c.stem), f"\\chapter{{{c.title}}}", f"\\label{{chap:{c.stem}}}", ""]
        if c.text.strip():
            parts += [c.text.strip(), ""]
        for n in c.nodes:
            if n.section:
                parts += [f"\\section{{{n.section}}}", ""]
            parts += [node_tex(n)]
        files[CHAPTER_DIR / f"{c.stem}.tex"] = "\n".join(parts)
        inputs.append(f"\\input{{chapters/{c.stem}}}")
    if references:
        bib = [GENERATED.format(stem="*"), "\\bibchapter", "\\begin{thebibliography}{RW97}"]
        for r in references:
            bib.append(f"\\bibitem[{r['label']}]{{{r['key']}}} {r['text'].strip()}")
        bib.append("\\end{thebibliography}")
        files[CHAPTER_DIR / "references.tex"] = "\n".join(bib) + "\n"
        inputs.append("\\input{chapters/references}")
    files[SRC / "content.tex"] = GENERATED.format(stem="*") + "\n".join(inputs) + "\n"
    return files


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if a generated file would change")
    ap.add_argument("--stubs", action="store_true", help="draft entries from the page text where none exist")
    ap.add_argument("--missing", action="store_true", help="list closure nodes with no cached page")
    args = ap.parse_args()

    if args.missing:
        _, entries, _ = load_curated()
        by_name = load_manifest()
        roots = [name for name, (_, e) in entries.items() if e.get("root")]
        for name in sorted(import_closure(roots, by_name)):
            if page(name) is None:
                print(f"{name}\t{by_name[name][0]['theorem_id']}")
        return

    chapters, nodes, references, stubs, deps, links = build(args.stubs)
    files = render(chapters, references, links)
    stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
    old = {p for p in CHAPTER_DIR.glob("*.tex")} - set(files)
    if args.check:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        for p in sorted(old):
            print(f"no longer generated: {p.relative_to(ROOT)}")
        sys.exit(1 if stale or old else 0)
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    for p in old:
        p.unlink()
    for name in stubs:
        print(f"draft: {name} (page text, unchecked)", file=sys.stderr)
    per_chapter = ", ".join(f"{c.stem} {len(c.nodes)}" for c in chapters if c.nodes)
    print(f"{len(nodes)} nodes from {len(deps)} Prove2Me nodes; {per_chapter}")


if __name__ == "__main__":
    main()
