/-
# The closure theorem

The central claim of the accompanying note (not included here; see the
README for the statement).

Let `u ≠ 0` be a hypothetical counterexample to Diaz's conjecture: `exp u`
algebraic and `u * conj u` algebraic.  Then `conj u = ρ / u`, so the
conjugate of `u` is a rational function of `u` with coefficients in the
base field.  The field generated by `u` is therefore stable under complex
conjugation, and carries it as a *ring* involution.

The point of formalizing this rather than the analytic obstructions is
that this is where the one real error in the note lived.  An earlier
draft called the involution a `ℚ̄`-algebra involution, which asserts that
it fixes every algebraic number.  It does not, and `conj_not_linear`
below is that error stated as a refuted proposition.

Everything here is stated for an arbitrary conjugation-stable subfield
`K ⊆ ℂ`, which is all the argument uses; the intended `K` is the field of
algebraic numbers.
-/
import Mathlib
import Diaz.Axioms

open ComplexConjugate

namespace Diaz

variable (K : Subfield ℂ) (u : ℂ)

/-- The subfield of `ℂ` generated by `K` together with `u`. -/
noncomputable def hull : Subfield ℂ := Subfield.closure ((K : Set ℂ) ∪ {u})

variable {K u}

theorem mem_hull_of_mem_base {z : ℂ} (hz : z ∈ K) : z ∈ hull K u :=
  Subfield.subset_closure (Or.inl hz)

theorem self_mem_hull : u ∈ hull K u :=
  Subfield.subset_closure (Or.inr rfl)

/-! ## Two derivations, so that hypotheses assuming them can go -/

/-- A transcendental element is non-zero: `0` is a root of `X`. -/
theorem transcendental_ne_zero {F : Type*} [Field F] [Algebra F ℂ] {z : ℂ}
    (h : Transcendental F z) : z ≠ 0 := by
  rintro rfl
  exact h isAlgebraic_zero

/-- An element outside a subfield is non-zero, subfields containing `0`. -/
theorem ne_zero_of_notMem {K : Subfield ℂ} {z : ℂ} (h : z ∉ K) : z ≠ 0 := by
  rintro rfl
  exact h K.zero_mem

/-! ## The identity the whole argument rests on -/

/-- With `ρ = u * conj u`, the conjugate of `u` is `ρ / u`.

Trivial as algebra, and it is the entire content of the closure theorem:
`conj u` is not an independent quantity but a rational function of `u`
over the base field.  Everything else follows. -/
theorem conj_eq_rho_div (hu : u ≠ 0) : (u * conj u) / u = conj u := by
  field_simp

/-! ## The hull is conjugation-stable -/

/-- Complex conjugation maps `hull K u` into itself, given that `K` is
conjugation-stable and contains `ρ = u * conj u`. -/
theorem conj_mem_hull (hK : ∀ z ∈ K, conj z ∈ K) (hu : u ≠ 0)
    (hrho : u * conj u ∈ K) :
    ∀ z ∈ hull K u, conj z ∈ hull K u := by
  intro z hz
  induction hz using Subfield.closure_induction with
  | mem x hx =>
      rcases hx with hx | hx
      · exact mem_hull_of_mem_base (hK x hx)
      · rw [Set.mem_singleton_iff] at hx
        subst hx
        rw [← conj_eq_rho_div hu]
        exact div_mem (mem_hull_of_mem_base hrho) self_mem_hull
  | one => simp
  | add x y _ _ hx hy => simpa using add_mem hx hy
  | neg x _ hx => simpa using neg_mem hx
  | inv x _ hx => simpa using inv_mem hx
  | mul x y _ _ hx hy => simpa using mul_mem hx hy

/-! ## The involution is not linear over the base

This is the corrected form of the statement.  It is short, and it is the
proposition an earlier draft of the note asserted the negation of. -/

/-- Conjugation is **not** `K`-linear once `K` contains a non-real number.

A `K`-linear map `f` would satisfy `f (a * z) = a * f z` for `a ∈ K`;
taking `z = 1` forces `conj a = a`, so only a totally real base field
could carry conjugation as a linear map.  Since the intended base is the
algebraic numbers, which contain `i`, conjugation on the hull is a ring
involution and nothing stronger. -/
theorem conj_not_linear {a : ℂ} (ha : conj a ≠ a) :
    ¬ (∀ z : ℂ, conj (a * z) = a * conj z) := by
  intro h
  exact ha (by simpa using h 1)

/-- The form actually needed: conjugation is not `K`-linear *on the hull*.

The refuted claim is about the hull, and `∀ z ∈ hull` is weaker than
`∀ z : ℂ`, so its negation is the stronger statement.  It is free: the
witness `z = 1` lies in the hull. -/
theorem conj_not_linear_hull {a : ℂ} (hne : conj a ≠ a) :
    ¬ (∀ z ∈ hull K u, conj (a * z) = a * conj z) := by
  intro h
  exact hne (by simpa using h 1 (hull K u).one_mem)

/-- Concretely: conjugation is not linear over any base containing `i`. -/
theorem conj_not_linear_of_I :
    ¬ (∀ z : ℂ, conj (Complex.I * z) = Complex.I * conj z) := by
  apply conj_not_linear
  intro h
  rw [Complex.conj_I] at h
  exact Complex.I_ne_zero (by linear_combination -h / 2)

/-! ## Rigidity: the hull admits no second conjugation -/

/-- Two ring homomorphisms of `ℂ` agreeing on `K` and at `u` agree on the
whole hull.  This is the "a homomorphism is determined by these data"
step of the closure theorem's proof. -/
theorem eqOn_hull (f g : ℂ →+* ℂ) (hK : ∀ z ∈ K, f z = g z) (hu : f u = g u) :
    ∀ z ∈ hull K u, f z = g z := by
  intro z hz
  induction hz using Subfield.closure_induction with
  | mem x hx =>
      rcases hx with hx | hx
      · exact hK x hx
      · rw [Set.mem_singleton_iff] at hx; subst hx; exact hu
  | one => simp
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
  | neg x _ hx => rw [map_neg, map_neg, hx]
  | inv x _ hx => rw [map_inv₀, map_inv₀, hx]
  | mul x y _ _ hx hy => rw [map_mul, map_mul, hx, hy]

/-! ## Transcendence, and the model -/

/-- A counterexample to Diaz's conjecture is transcendental.  The only
imported input is Hermite–Lindemann. -/
theorem transcendental_of_candidate (hu : u ≠ 0)
    (hexp : IsAlgebraic ℚ (Complex.exp u)) : Transcendental ℚ u :=
  hermite_lindemann hu hexp

/-- Transcendence over `ℚ` upgrades to transcendence over any base
algebraic over `ℚ` — in particular over the algebraic numbers, which is
the intended base.

Without this the imported axiom is a dead leaf: the results above take
transcendence over the base as a hypothesis, while Hermite–Lindemann
supplies it only over `ℚ`. The algebraicity hypothesis is necessary
rather than decorative: for a base containing `u` the conclusion is
false. -/
theorem transcendental_of_base {L : Subfield ℂ} [Algebra.IsAlgebraic ℚ (↥L)]
    {z : ℂ} (h : Transcendental ℚ z) : Transcendental (↥L) z :=
  fun hcon => h (hcon.restrictScalars ℚ)

/-- The bridge, assembled: a candidate is transcendental over the base. -/
theorem transcendental_candidate_over_base {L : Subfield ℂ}
    [Algebra.IsAlgebraic ℚ (↥L)] (hu : u ≠ 0)
    (hexp : IsAlgebraic ℚ (Complex.exp u)) : Transcendental (↥L) u :=
  transcendental_of_base (transcendental_of_candidate hu hexp)

end Diaz
