/-
# The formal exponential of the model

The last clause of `prop:model`: the model carries a homomorphism

    Exp₀ (a T + b σT) = 2 ^ (a + b)

into the algebraic numbers, commuting with the involution. Two further
facts about it carry the weight of the argument, and both are proved
here:

* its kernel is the *divisible* line `a + b = 0`;
* its image `2^ℚ` is *torsion-free*.

**A caveat, and it matters.**  These are facts about *this* `Exp₀`, not
about the model.  The only constraints the model puts on a formal
exponential are that it be a homomorphism into the algebraic numbers
commuting with the involution, and those are also met by

    Exp'(a, b) = exp(2πi(a - b)) * 2 ^ (a + b),

whose values are a root of unity times a rational power of two, hence
algebraic, and whose kernel is the rank-one *lattice* generated by
`(1/2, -1/2)`.  So a lattice kernel does not by itself escape the model.
What escapes is the archimedean size of `2πi` — the constant `π²` — not
discreteness as such.

Coordinates are used rather than elements of the plane: `t` and `conj t`
are `ℚ`-independent (`Model.lean`), so `(a, b) ↦ a t + b conj t` is a
bijection onto the plane and nothing is lost. The involution acts by
swapping coordinates.
-/
import Mathlib
import Diaz.Model

open ComplexConjugate

namespace Diaz

/-! ## `2 ^ r = 1` only at `r = 0` -/

theorem two_rpow_eq_one_iff (r : ℝ) : (2 : ℝ) ^ r = 1 ↔ r = 0 := by
  rw [Real.rpow_def_of_pos (by norm_num), Real.exp_eq_one_iff]
  constructor
  · intro h
    rcases mul_eq_zero.mp h with h | h
    · exact absurd h (by positivity)
    · exact h
  · rintro rfl; ring

/-! ## Rational powers of two are algebraic -/

/-- `2 ^ q` is algebraic for every rational `q`: it is a root of
`X ^ q.den - 2 ^ q.num`. -/
theorem isAlgebraic_two_rpow (q : ℚ) : IsAlgebraic ℚ ((2 : ℝ) ^ (q : ℝ)) := by
  refine ⟨Polynomial.X ^ q.den - Polynomial.C ((2 : ℚ) ^ q.num), ?_, ?_⟩
  · exact (Polynomial.monic_X_pow_sub_C _ q.den_nz).ne_zero
  · have hden : (q.den : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr q.den_nz
    have hq : (q : ℝ) * (q.den : ℝ) = (q.num : ℝ) := by
      have h : (q : ℝ) = (q.num : ℝ) / (q.den : ℝ) := by
        exact_mod_cast (Rat.num_div_den q).symm
      rw [h]; field_simp
    simp only [map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
    rw [← Real.rpow_natCast ((2 : ℝ) ^ (q : ℝ)) q.den, ← Real.rpow_mul (by norm_num), hq,
      Real.rpow_intCast 2 q.num]
    push_cast
    norm_num

/-! ## The formal exponential -/

/-- `Exp₀ (a, b) = 2 ^ (a + b)`, the formal exponential of the model. -/
noncomputable def Exp0 (x : ℚ × ℚ) : ℝ := (2 : ℝ) ^ ((x.1 + x.2 : ℚ) : ℝ)

theorem Exp0_pos (x : ℚ × ℚ) : 0 < Exp0 x := Real.rpow_pos_of_pos (by norm_num) _

theorem Exp0_ne_zero (x : ℚ × ℚ) : Exp0 x ≠ 0 := (Exp0_pos x).ne'

/-- `Exp₀` is a homomorphism from the plane to `ℝ^×`. -/
theorem Exp0_add (x y : ℚ × ℚ) : Exp0 (x + y) = Exp0 x * Exp0 y := by
  simp only [Exp0, Prod.fst_add, Prod.snd_add]
  rw [← Real.rpow_add (by norm_num)]
  push_cast
  ring_nf

/-- `Exp₀` commutes with the involution.  In coordinates the involution
swaps `a` and `b`; the values are real, so complex conjugation fixes
them, and `a + b` is symmetric. -/
theorem Exp0_swap (x : ℚ × ℚ) : Exp0 (x.2, x.1) = Exp0 x := by
  simp only [Exp0]
  ring_nf

/-- The form the model actually needs: `Exp₀ ∘ σ = conj ∘ Exp₀`, stated
with the conjugation rather than only with the coordinate swap. -/
theorem Exp0_swap_conj (x : ℚ × ℚ) :
    ((Exp0 (x.2, x.1) : ℂ)) = (starRingEnd ℂ) ((Exp0 x : ℂ)) := by
  rw [Exp0_swap]
  simp [Complex.conj_ofReal]

/-- Every value of `Exp₀` is algebraic: the model really is a model of
the *arithmetic* situation, not merely of the field structure. -/
theorem Exp0_isAlgebraic (x : ℚ × ℚ) : IsAlgebraic ℚ (Exp0 x) :=
  isAlgebraic_two_rpow _

/-! ## The two defects

These are the statements §4 of the note turns on. -/

/-- **The kernel of this `Exp₀` is the divisible line `a + b = 0`.**

A property of this choice, not of the model — see the caveat in the file
header, where a variant with a lattice kernel is given. -/
theorem Exp0_eq_one_iff (x : ℚ × ℚ) : Exp0 x = 1 ↔ x.1 + x.2 = 0 := by
  rw [Exp0, two_rpow_eq_one_iff]
  exact_mod_cast Iff.rfl

/-- **The image of this `Exp₀` is torsion-free.**

A standard kernel `ℤω` makes `Exp (pω/m)` a primitive `m`-th root of
unity, so the image would have to contain every root of unity; `2^ℚ`
contains none but `1`. Again a property of this choice: the variant in
the file header has both a lattice kernel and torsion in its image. -/
theorem Exp0_pow_eq_one_iff (x : ℚ × ℚ) {n : ℕ} (hn : n ≠ 0) :
    Exp0 x ^ n = 1 ↔ Exp0 x = 1 := by
  constructor
  · intro h
    have hx : Exp0 x ^ n = (2 : ℝ) ^ (((x.1 + x.2) * n : ℚ) : ℝ) := by
      rw [Exp0, ← Real.rpow_natCast ((2:ℝ) ^ (((x.1 + x.2 : ℚ)) : ℝ)) n,
        ← Real.rpow_mul (by norm_num)]
      push_cast
      ring_nf
    rw [hx, two_rpow_eq_one_iff] at h
    rw [Exp0_eq_one_iff]
    have hn' : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr hn
    have : ((x.1 + x.2) * n : ℚ) = 0 := by exact_mod_cast h
    rcases mul_eq_zero.mp this with h' | h'
    · exact h'
    · exact absurd h' hn'
  · intro h; rw [h, one_pow]

/-! ## The configuration is realised -/

/-- **The analogue of Diaz's conjecture is false in the model.**

There is a non-zero element of the plane whose product with its conjugate
lies in `K` and which carries an algebraic formal exponential.  This is
the claim the closure theorem is pointed at, and it is what makes the
absence of a contradiction more than a failure to find one. -/
theorem model_falsifies {K : Subfield ℂ} {t : ℂ}
    (hρ : t * conj t ∈ K) (ht0 : t ≠ 0) :
    ∃ a b : ℚ, ((a : ℂ) * t + (b : ℂ) * conj t) ≠ 0
      ∧ IsAlgebraic ℚ (Exp0 (a, b))
      ∧ ((a : ℂ) * t + (b : ℂ) * conj t)
          * conj ((a : ℂ) * t + (b : ℂ) * conj t) ∈ K :=
  ⟨1, 0, by simpa using ht0, Exp0_isAlgebraic _, by simpa using hρ⟩

end Diaz
