/-
# Definitions for the six-exponentials mission, as the platform states them

Mirrored from Prove2Me's `SX` definition node. The Diaz node
`DiazModulus.six_exponentials` rests on `SX.six_exponentials_of_numberField`, which is
stated in these terms, so they are carried here verbatim.
-/
import Mathlib

/-!
# Definitions bundle for the six exponentials theorem

Everything the five statements of the `six-exp` ladder need that Mathlib (rev
`0df444a3`) does not have. Nothing here is a mathematical result: four `def`s,
five structural lemmas whose proofs are pure bookkeeping, and one computation
(`exp_expExponent_mul_latticeSum`) that is the arithmetic bridge every rung uses.
-/

open Complex Finset

namespace SX

variable {d l : ℕ}

/-- The box of multi-indices `λ : Fin d → ℕ` with every coordinate `< L`.
This is the index set of the coefficients of the auxiliary exponential polynomial. -/
def box (d L : ℕ) : Finset (Fin d → ℕ) := Fintype.piFinset fun _ => Finset.range L

@[simp] theorem mem_box {L : ℕ} {lam : Fin d → ℕ} :
    lam ∈ box d L ↔ ∀ i, lam i < L := by
  simp [box, Fintype.mem_piFinset]

/-- The lattice point `∑ j, m j • y j`. As `m` ranges over `ℕ ^ l` these are the points at
which the auxiliary function is made to vanish. -/
def latticeSum (y : Fin l → ℂ) (m : Fin l → ℕ) : ℂ := ∑ j, (m j : ℂ) * y j

/-- The exponent `∑ i, λ i • x i` attached to a multi-index `λ`. -/
def expExponent (x : Fin d → ℂ) (lam : Fin d → ℕ) : ℂ := ∑ i, (lam i : ℂ) * x i

/-- The auxiliary function `F(z) = ∑_{λ ∈ box d L} p λ * exp (⟨λ, x⟩ * z)`:
a `ℤ`-linear combination of the monomials in `exp (x 0 * z), …, exp (x (d-1) * z)`
of partial degree `< L`. -/
noncomputable def expSum (x : Fin d → ℂ) (L : ℕ) (p : (Fin d → ℕ) → ℤ) : ℂ → ℂ :=
  fun z => ∑ lam ∈ box d L, (p lam : ℂ) * Complex.exp (expExponent x lam * z)

/-- `f` has order of growth at most `ρ`. Mathlib has no order-of-growth theory at this
revision; the auxiliary function of Schneider's method has order `1`, and this predicate is
what an abstract form of the criterion would quantify over. -/
def OrderAtMost (f : ℂ → ℂ) (ρ : ℝ) : Prop :=
  ∃ C c : ℝ, 0 < C ∧ 0 < c ∧ ∀ z : ℂ, ‖f z‖ ≤ C * Real.exp (c * ‖z‖ ^ ρ)

theorem differentiable_expSum (x : Fin d → ℂ) (L : ℕ) (p : (Fin d → ℕ) → ℤ) :
    Differentiable ℂ (expSum x L p) := by
  unfold expSum
  fun_prop

@[simp] theorem expSum_zero (x : Fin d → ℂ) (L : ℕ) (z : ℂ) :
    expSum x L (fun _ => 0) z = 0 := by simp [expSum]

@[simp] theorem latticeSum_zero (y : Fin l → ℂ) : latticeSum y (fun _ => 0) = 0 := by
  simp [latticeSum]

/-- The arithmetic bridge: at a lattice point the auxiliary function's exponentials are
monomials in the six numbers `exp (x i * y j)`. This is what puts the values of `expSum`
inside the number field generated by them. -/
theorem exp_expExponent_mul_latticeSum (x : Fin d → ℂ) (y : Fin l → ℂ)
    (lam : Fin d → ℕ) (m : Fin l → ℕ) :
    Complex.exp (expExponent x lam * latticeSum y m)
      = ∏ i, ∏ j, Complex.exp (x i * y j) ^ (lam i * m j) := by
  have hsum : expExponent x lam * latticeSum y m
      = ∑ i, ∑ j, ((lam i * m j : ℕ) : ℂ) * (x i * y j) := by
    rw [expExponent, latticeSum, Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    push_cast
    ring
  rw [hsum, Complex.exp_sum]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [Complex.exp_sum]
  exact Finset.prod_congr rfl fun j _ => Complex.exp_nat_mul _ _

end SX
